module.exports = {
  settings: {
    tvGuide: 'tvguide',
    time: 'time',
    temperature: 'temperature',
    font: 'font',
  },
  temperatureFormat: {
    fahrenheit_old: 'ºF',
    celsius_old: 'ºC',
    fahrenheit: 'F',
    celsius: 'C',
    fahrenheitFormat: 'FAHRENHEIT (ºF)',
    celciusFormat: 'CELCIUS (ºC)',
  },
  tvGuideFormat: {
    classic: 'CLASSIC',
    modern: 'MODERN',
  },
  timeFormat: {
    hour12: '12 HOUR',
    hour24: '24 HOUR',
  },
  largeFontSize: {
    on: 'ON',
    off: 'OFF',
  },
  index: 'index',
  player: 'player',
  laneIndex: 'laneIndex',
  swimlaneName: 'swimlaneName',
  swimlaneIndex: 'swimlaneIndex',
  tileIndex: 'tileIndex',
  swimlaneHeadings: {
    featuredChannels: 'Featured Channels',
    sports: 'Sports',
    exploreMore: 'Explore More...',
  },
  swimlaneText: {
    newsWeatherCorouselText: 'news & weather',
    communityInfoCorouseltext: 'community information',
    forYouCorouselText: 'for you',
    featuredChannelsCorouselText: 'featured channels',
    sportsCarouselText: 'sports',
  },
  time: {
    AM: 'AM',
    PM: 'PM',
  },
  temperatureFormatFireTv: {
    fahrenheit: '°F',
    celsius: '°C',
  },
  tileNo: 'tileNo',
  titleDetails: {
    title: 'Moon Knight',
    overview:
      'Steven Grant learns that he may be a superhero, but may also share a body with a ruthless mercenary.',
    classification: '16+',
  },
  titleName: 'titleName',
  datatestid: 'data-testid',
  lockIcon: 'LockIcon',
  unlockIcon: 'LockOpenIcon',
  classInp: 'ClassInp',
  allAges: 'ALL AGES', // G
  ages2To6: 'AGES 2-6', // Y
  ages7AndUp: 'AGES 7 AND UP', // Y7
  ages7AndUpFV: 'AGES 7 AND UP (FANTASY VIOLENCE)', // Y7FV
  parentalGuidance: 'PARENTAL GUIDANCE RECOMMENDED', // PG
  parentalGuidance13: 'PARENTS STRONGLY CAUTIONED', // PG13
  under14: 'MAY NOT BE SUITABLE FOR THOSE UNDER 14', // 14
  under18: 'MAY NOT BE SUITABLE FOR THOSE UNDER 18', // MA
  restricted: 'RESTRICTED', // R
  adultsOnly: 'ADULTS ONLY', // NC17
  unratedContent: 'UNRATED CONTENT', // NA
  pin1: 1,
  pin2: 1,
  pin3: 1,
  pin4: 1,
  wrongPin4: 2,
  G: 'TVG',
  Y: 'TVY',
  Y7: 'TVY7',
  Y7FV: 'TVY7FV',
  PG: 'TVPG',
  PG13: 'PG13',
  TV14: 'TV14',
  MA: 'TVMA',
  R: 'R',
  NC17: 'NC17',
  NA: 'NA',
  pin5: 1,
  pin6: 2,
  pin7: 3,
  pin8: 4,
  buttonText: {
    watchNow: 'WATCH NOW',
    play: 'PLAY',
    learnMore: 'LEARN MORE',
  },
  progressBarWidthRegExp: /width: (\d+(?:\.\d+)?|\.\d+)%/,
  programDurationRegex: '(([01]?[0-9]):([0-5][0-9]) ([AaPp][Mm]))',
  timeLeftRegex: '[0-9]+M Left',

  videoTitleDetails: {
    videoTitle: 'The Big Bang Theory',
    videoOverview:
      'Brilliant physicist roommates Leonard and Sheldon meet their new neighbor Penny, who begins showing them that as much as they know about science, they know little about actual living',
    videoClassification: 'Comedy, Romance',
    videoSeasons: '16+',
  },
  videoPlayers: [
    'PRIME VIDEO',
    'GOOGLE PLAY',
    'HBO MAX',
    'ITUNES',
    'VUDU',
    'YOUTUBE',
  ],

  guide: {
    colorLabel: 'color',
    whiteColor: 'rgba(255, 255, 255, 1)',
    fontWeight: 'font-weight',
    bold: '700',
    normal: '400',
    png: '.png',
    player: 'player',
    unrated: 'NR',
  },
  highlightedText: 'rgba(255, 255, 255, 1)',
  dummyPassword: 'Dummy@123',
  dummyPassword1: 'Dummy@1234',
  typeText: 'type',
  passwordText: 'password',
  text: 'text',
  valueText: 'value',
  search: {
    franchiseAssetChannelTitle: 'Friends',
    invalidSearchTitle: 'ghijklZ',
    channelName: 'ESPN',
  },
  orientation: {
    portrait: 'PORTRAIT',
    landscape: 'LANDSCAPE',
  },
  searchTitle: 'SLASHER',
  okayBtn: 'OKAY',
  navigationMenu: {
    home: 'Home',
    watch: 'Watch',
    tvGuide: 'TV Guide',
    settings: 'Settings',
    search: 'Search',
    cast: 'Cast',
    onDemand: 'On Demand',
    communityInfo: 'Community Info',
    myStay: 'My Stay',
    hotelInfo: 'Hotel Info',
    apps: 'Apps',
  },
  remoteKey: {
    left: 'left',
    right: 'right',
    up: 'up',
    down: 'down',
    ok: 'select',
    back: 'back',
    backspace: 'backspace',
  },
  timeWait: {
    defaultVisibleElement: 5,
    loadingVideo: 40,
    loadingMessage: 60,
    getTotalChannel: 1000,
    checkingPlay: 5,
    loading: 10,
    checkingIcon: 3,
    getTotalProgram: 1000,
  },
  temperatureFormatRoku: {
    fahrenheit: 'FAHRENHEIT (°F)',
    celsius: 'CELSIUS (°C)',
  },
  settingsOptions: {
    appSettings: 'APP SETTINGS',
    faqs: 'FAQS',
    legalAndAbout: 'LEGAL & ABOUT',
    signIn: 'SIGN IN',
    signOut: 'SIGN OUT',
    confirmButton: 'CONFIRM',
    parentalControls: 'PARENTAL CONTROLS',
    setUpPin: 'SETUP A PIN',
    account: 'ACCOUNT',
  },
  accountOptions: {
    changeEmail: 'CHANGE EMAIL',
    changePassword: 'CHANGE PASSWORD',
    deactivateYourAccount: 'DEACTIVATE YOUR ACCOUNT',
    deleteYourAccount: 'DELETE YOUR ACCOUNT',
    linkDescription: 'Open the below link on your Desktop/Laptop',
    qrCodeDescription: 'Scan the QR Code to sign on your mobile device',
  },
  sportsSwimlanes: ['NBA', 'NHL', 'MLB'],
  onDemand: {
    platformNames: {
      HBO: 'HBO',
      'HBO MAX': 'HBO',
      'PARAMOUNT+': 'Paramount+',
      'DISNEY+': 'Disney+',
      'NETFLIX+': 'Netflix',
      'PRIME VIDEO': 'Prime',
      HULU: 'Hulu',
      'PEACOCK PREMIUM': 'Peacock',
    },
  },
  timesFormat: {
    tvGuide12H: 'hh:mm A',
    tvGuide24H: 'HH:mm',
    sports12h: 'h:mmA M/D',
    sports24h: 'HH:mm M/D',
    androidSports12h: 'hh:mm A MM/DD',
    androidSports24h: 'HH:mm MM/DD',
  },
  totalProgram: 20,
  teamStatsText: 'Team Stats',
  swimlanesName: {
    sports: 'SPORTS',
    sportsWeather: 'Sports & Weather',
    sportsAndWeather: 'Sports and Weather',
    sportsAndLocalWeather: 'Sports Scores and Local Weather',
  },
  platform: {
    firetv: 'firetv',
    browser: 'browser',
    roku: 'roku',
    android: 'mobile',
    lg: 'lg',
    evolve2: 'android',
  },
  sportsLeagues: {
    mlb: 'mlb',
    nba: 'nba',
    nhl: 'nhl',
    nfl: 'nfl',
  },
  leagues: ['nfl', 'nhl', 'nba', 'mlb'],
  dummyEmail: 'dummyyemail1234@os.com',
  dummyEmail2: 'dummyemail12345@os.com',
  invalidEmail: 'dummy123',
  formatOptions: {
    time: 'TIME FORMAT',
    temperature: 'TEMPERATURE FORMAT',
  },
  totalSettingOptions: 7,
  regularExpressions: {
    _24HrsDateTimeExp:
      '^([0-2][0-9]|0?[1-9]):[0-5][0-9]\\s(1[0-2]|0?[0-9])/([0-3][0-9]|0?[0-9])',
    _12HrsDateTimeExp:
      '^(1[0-2]|0?[1-9]):[0-5][0-9](AM|PM)\\s(1[0-2]|0?[0-9])/([0-3][0-9]|0?[0-9])',
    _12HrsTimeExp: '(^[0-1]|[0-9]):([0-5][0-9])\\s([aApP][mM])',
    _24HrsTimeExp: '(^[0-2][0-9]):([0-5][0-9])',
  },
  esc: 'Escape',
  url: {
    beta: 'beta',
    davita: 'davita',
  },
  module: {
    general: 'general',
    accountDetails: 'accountDetails',
    parentalLock: 'parentalLock',
    changePin: 'changePin',
    watchLater: 'watchLater',
    changePassword: 'changePassword',
    prod: 'prod',
  },
  numberScrollToLastRating: 10,
  parentalControlsRating: [
    'TVG',
    'TVY',
    'TVY7',
    'TVY7FV',
    'TVPG',
    'PG13',
    'TV14',
    'TVMA',
    'R',
    'NC17',
    'NA',
  ],
  parentalControlsSettings: {
    changePinButton: 'CHANGE PIN',
    removePcButton: 'REMOVE PARENTAL CONTROLS',
  },
  signIn: {
    colorLabel: 'color',
    whiteColor: 'rgba(255, 255, 255, 1)',
    userFormat: 'dummyRandomNumber@os.com',
    userPassword: 'Beta@123',
    partialEmail: 'beta20',
    invalidEmailText: 'Email address is not valid',
  },
  sportTile: 'SPORTS',
  signUp: {
    dummyEmail: 'dummyemail123@os.com',
    invalidEmail: 'dummy123',
    passwordWithShortLength: 'abc',
    passwordWithNoUpperCase: 'abcdefgh',
    passwordWithNoNumber: 'Abcdefgh',
    dummyPassword1: 'Test@123',
    dummyPassword2: 'Test@321',
    passwordWithNoSpecialCharacter: 'Abcd1234',
  },
  carousel: 'hero-carousel',
  adSpaceCarousel: 'carousel--728x90px',
  swimlane: 'swimlane',
  widgetType: {
    sports: 'widget--sports',
    live: 'widget--live-channel',
    staticAd: 'widget--static-ad',
    moreInfo: 'widget--more-info',
    notification: 'widget--notification',
    weather: 'widget--weather',
    video: 'widget--more-info-video',
  },
  widgetTitle: {
    exploreMore: 'Explore More...',
  },
  maxSwimlanesSports: 4,
  maxResetHome: 6,
  iterations: 8,
  gameStatus: {
    live: 'IN_PROGRESS',
    upcoming: 'UPCOMING',
    completed: 'COMPLETED',
    cancelled: 'CANCELLED',
  },
  devTools: {
    password: 'OnStreamQA123!',
    smartboxID: {
      hospitality: 'HOTEL',
      mdu: 'AUTOMATION',
    },
  },
  settingsSubHeadings: {
    appSettings: {
      tvGuideFormat: 'TV GUIDE FORMAT',
      enableLargeFontSize: 'ENABLE LARGE FONT SIZE',
      timeFormat: 'TIME FORMAT',
      temperatureFormat: 'TEMPERATURE FORMAT',
    },
    legalAndAbout: {
      termsOfService: 'TERMS OF SERVICE',
      termsOfServiceContent:
        'To read our terms and conditions, please go here: https://www.dish.com/terms-conditions/',
      privacyPolicy: 'PRIVACY POLICY',
      privacyPolicyContent:
        'To read our service agreements, please go here: https://www.dish.com/service-agreements/',
    },
  },
  widgets: {
    largeWidget: 'swimlane--widgets-large',
    smallWidget: 'swimlane--widgets',
    carousel: 'hero-carousel',
  },
  emptyField: '',
  emptyFavoritesMessage: 'You haven’t added anything to favorites yet',
  emptyFavoritesMessageCTV: 'Uh oh! No Favorites added yet.',

  pages: {
    homePage: 'homePage',
    hotelInfoPage: 'hotelInfoPage',
    watchPage: 'watchPage',
    myStayPage: 'myStayPage',
    mediaCastingPage: 'mediaCastingPage',
    settingsPage: 'settingsPage',
    appsPage: 'appsPage',
  },
  pageElements: {
    homePage: {
      welcomeBanner: 'welcomeBanner',
      propertyLogo: 'propertyLogo',
    },
  },
  welcomeBanner: {
    greeting: 'greeting',
    message: 'message',
    subHeadline: 'subHeadline',
  },
  tvGuideGenreFilterTabs: {
    favourites: 'FAVOURITES',
    allChannels: 'ALL CHANNELS',
    sports: 'SPORTS',
    movies: 'MOVIES',
    news: 'NEWS',
    kids: 'KIDS',
  },
  menuKeys: {
    cast: 'showCast',
    tvGuide: 'showTvGuide',
    onDemand: 'showOnDemand',
    dvr: 'showRecordings',
    settings: 'showSettings',
    search: 'showSearch',
    home: 'showHome',
  },
  menuItems: {
    cast: 'cast',
    tvGuide: 'tvGuide',
    onDemand: 'onDemand',
    dvr: 'dvr',
    search: 'search',
    home: 'home',
    settings: 'settings',
  },
  appSettingKeys: {
    tsbEnabled: 'tsbEnabled',
    showLargeFontSelection: 'showLargeFontSelection',
    showMiniGuide: 'showMiniGuide',
    showSignIn: 'showSignIn',
    showParentalControl: 'showParentalControl',
  },
  legalKeys: {
    contact: 'contact',
    termsOfUse: 'termsOfUse',
    privacyPolicy: 'privacyPolicy',
  },
  faqKey: 'faq',
  castKeys: {
    clientSSID: 'clientSSID',
    googleCastIp: 'googleCastIp',
  },
  tvGuideFilters: {
    favorites: 'FAVOURITES',
    all_channels: 'ALL CHANNELS',
    sports: 'SPORTS',
    movies: 'MOVIES',
    news: 'NEWS',
    kids: 'KIDS',
  },
  propertyType: {
    hospitality: 'hospitality',
    mdu: 'mdu',
  },
  propertyId: {
    debug: {
      hospitality: '2a8158fc-2ba6-4963-99f0-ab605a02f790', // HOTEL
      mdu: 'f98d4863-648e-4d03-86fd-8c5c34072ea4', // AUTOMATION
    },
    release: {
      hospitality: '65ad9524-377e-4484-8c60-e1b143a21946', //HOTEL
      mdu: '65258c49-c1f1-48f5-8802-3218cdbc5ff5', //AUTOMATION
    },
  },
  buildType: {
    debug: 'debug',
    release: 'release',
  },
  tileName: {
    watch: 'Watch',
    hotelInfo: 'Hotel Info',
    myStay: 'My Stay',
    tvGuide: 'TV Guide',
    settings: 'Settings',
  },
  onDemandSwimlane: {
    trendingContents: 'Trending Contents',
    popularShows: 'Popular Shows',
    popularMovies: 'Popular Movies',
  },
  notSupportedWidgetOnRoku: {
    widgetDeepLink: 'widget--deep-link',
    widgetMoreInfo: 'widget--more-info',
    widgetLiveChannel: 'widget--live-channel',
  },
  maxNoOfWidgets: 32,
  maxNavBarItems: 10,
  maxNoOfTilesInAScreen: 7,
  maxAttempts: 10,
  maxNoOfChannelsTVGuide: 6,
  maxNoOfChannelsTVGuideForBrowser: 5,
  maxNoOfHomeTiles: 5,
};
